name: OWASP ZAP Integration with GitHub Actions

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Zap Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'http://testphp.vulnweb.com/'